djotali/billing/urls.py
# coding: utf8

from django.conf.urls import url

from djotali.billing import views

app_name = 'billing'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

djotali/campaigns/urls.py
# coding: utf8

from django.conf.urls import url, include

from djotali.campaigns import views
from djotali.campaigns.api import router

app_name = 'campaigns'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new$', views.CreateView.as_view(), name='new'),
    url(r'^(?P<campaign_id>\d+)/notify$', views.campaign_notify, name='notify_campaign'),
    url(r'^(?P<pk>\d+)/notifications$', views.NotificationsView.as_view(), name='notifications'),
    url(r'^(?P<pk>\d+)$', views.DetailView.as_view(), name='show'),
    url(r'^(?P<pk>\d+)/edit$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<campaign_id>\d+)/notifications/(?P<notification_id>\d+)/notify$', views.notify, name='core_notify'),
    # url(r'^(?P<message_id>[0-9]+)/$', views.IndexView.as_view(), name='index')
    url(r'^api/', include(router.urls, namespace='api_campaign'))
]

djotali/contacts/urls.py
# coding: utf-8

from django.conf.urls import url

from djotali.contacts import views

app_name = 'contacts'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new$', views.CreateContactView.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', views.EditContactView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.DeleteContactView.as_view(), name='delete'),
    url(r'^import$', views.ImportContactsView.as_view(), name='import'),
    url(r'^model.csv', views.CsvModelView.as_view(), name='csv_model'),
]

djotali/core/urls.py
# coding: utf8

app_name = 'core'
urlpatterns = [
    # url(r'^(?P<message_id>[0-9]+)/$', views.IndexView.as_view(), name='index')
]

djotali/profile/urls.py
# coding: utf-8
from django.conf.urls import url

from djotali.profile import views

app_name = 'profile'
urlpatterns = [
    url(r'^organization-users$', views.OrganizationUsersView.as_view(), name='organization-users'),
    url(r'^activate-users$', views.ActivateOrganizationUsersView.as_view(), name='activate-users'),
    url(r'^invite-users$', views.InviteOrganizationUserView.as_view(), name='invite-users'),
    url(r'^invitation$', views.InvitationView.as_view(), name='invitation'),
]

djotali/urls.py
# coding: utf-8
"""djotali URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from djotali.contacts.views import ContactViewSet, ContactsGroupsContactsViewSet
from djotali.profile.views import OrganizationsView

router = routers.DefaultRouter()
router.register(r'contacts', ContactViewSet)
router.register(r'contacts-groups/(?P<group_id>\d+)/contacts', ContactsGroupsContactsViewSet)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(reverse('dashboard:index'))),
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('djotali.core.urls')),
    url(r'^dashboard/', include('djotali.dashboard.urls')),
    url(r'^contacts/', include('djotali.contacts.urls')),
    url(r'^contacts-groups/', include('djotali.contacts.groups_urls')),
    url(r'^login/', TemplateView.as_view(template_name='core/login.html')),
    url(r'^campaigns/', include('djotali.campaigns.urls')),
    url(r'^billing/', include('djotali.billing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('djotali.profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/organizations/(?P<organization_name>[\S ]+)', OrganizationsView.as_view()),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token-auth/', obtain_jwt_token),
    url(r'^hijack/', include('hijack.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

djotali/dashboard/models.py
# coding: utf-8

djotali/campaigns/forms.py
# coding: utf-8

from django import forms

from djotali.campaigns.models import Campaign
from djotali.campaigns.widgets import CampaignContactsGroupBoundModelsSelectWidget, SmsWidget
from djotali.contacts.models import ContactsGroup
from djotali.core.forms import BaseForm
from djotali.core.widgets import DateTimeFieldWidget
from djotali.profile.models import Sender


class CampaignForm(BaseForm):
    class Meta:
        model = Campaign
        fields = ['name', 'start_date', 'message', 'contacts_group']

    name = forms.CharField(label='Nom')
    start_date = forms.DateTimeField(label='Lancement', widget=DateTimeFieldWidget)
    message = forms.Field(label='Message', widget=SmsWidget)
    contacts_group = forms.ModelChoiceField(label='Groupe de contacts', queryset=ContactsGroup.objects,
                                            widget=CampaignContactsGroupBoundModelsSelectWidget,
                                            empty_label='Tous les contacts', required=False)

    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.fields['contacts_group'].queryset = ContactsGroup.org_objects.get_queryset_for_organization(self.request.organization)
        self.fields['message'].widget.attrs['sender'] = Sender.org_objects.get_queryset_for_organization(self.request.organization).first().sender_id

djotali/contacts/forms.py
# coding: utf-8
import phonenumbers
from django.core.exceptions import ValidationError
from django.forms import CharField, Field, FileField
from django.forms.forms import Form
from django.forms.widgets import FileInput
from django.utils.translation import ugettext_lazy as _
from phonenumbers.phonenumberutil import NumberParseException

from djotali.contacts.models import Contact, ContactsGroup
from djotali.contacts.widgets import ContactsWidget
from djotali.core.forms import BaseForm


class ContactForm(BaseForm):
    # Max number of characters of a senegalese telephone number including whitespaces
    phone_number = CharField(initial='+221 ', label='Téléphone', max_length=17)
    first_name = CharField(label='Prénom')
    last_name = CharField(label='Nom')

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'phone_number']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        error_message = 'Le numéro de téléphone entré est erroné'
        try:
            if not phonenumbers.is_valid_number(phonenumbers.parse(phone_number, 'SN')):
                raise ValidationError(_(error_message), code='invalid')
        except NumberParseException:
            raise ValidationError(_(error_message), code='invalid')

        return phone_number


class ContactsGroupForm(BaseForm):
    name = CharField(label='Nom')
    contacts = Field(label='Contacts', widget=ContactsWidget)

    class Meta:
        model = ContactsGroup
        fields = ['name', 'contacts']


class ImportContactsForm(Form):
    file = FileField(widget=FileInput(attrs={'class': 'dropify'}))

djotali/core/forms.py
# coding: utf-8
from django.forms import ModelForm


class BaseForm(ModelForm):
    required_css_class = 'form-group'

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            setattr(self, 'request', kwargs.pop('request'))
        super(BaseForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        if hasattr(self, 'request'):
            self.instance.organization = self.request.organization
        return super().save(commit)

djotali/billing/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.views import generic

from djotali.billing.models import Credit, CampaignAllocatedCredit, Product


# TODO becomes a generic.ListView when we will introduce transactions
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'billing/show.html'
    queryset = Product.objects.get_published_products
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['credit'] = Credit.objects.get(organization=self.request.organization)
        allocated_credit = \
            CampaignAllocatedCredit.objects.filter(organization=self.request.organization).aggregate(Sum('allocated_credit'))['allocated_credit__sum']
        data['allocated_credit'] = allocated_credit if allocated_credit else 0
        return data

djotali/campaigns/views.py
# coding: utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.aggregates import Sum
from django.db.models.expressions import Case, When
from django.db.models.fields import IntegerField
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import generic
from django.utils.translation import gettext as _

from djotali.billing.models import Credit
from djotali.campaigns.forms import CampaignForm
from djotali.campaigns.models import Campaign, Notification
from djotali.campaigns.tasks import notify_campaign, notify_task, is_campaign_launched
from djotali.core.utils import is_celery_running
from djotali.core.views import paginate_in_context, RequestAwareFormViewMixin
from djotali.profile.decorators import organization_view

_broker_is_not_running_msg = 'Le broker est arrêté. Le lancement des campagnes est suspendu.'


@organization_view
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'campaigns/index.html'
    context_object_name = 'list_objects'
    paginate_by = 5
    queryset = Campaign.get_closest_campaigns_query_set()


@organization_view
class NotificationsView(LoginRequiredMixin, generic.DetailView):
    model = Campaign
    template_name = 'campaigns/notifications.html'
    context_object_name = 'campaign'

    def get_context_data(self, **kwargs):
        context = super(NotificationsView, self).get_context_data(**kwargs)
        campaign = self.object

        status = self.request.GET.get('status')
        context['status'] = status

        notifications = campaign.notifications
        if status is not None:
            notifications = notifications.filter(status=Notification.get_status_value(status))
        paginate_in_context(self.request, notifications, context, 'notifications')

        context['editable'] = not is_campaign_launched(campaign.id)

        return context


@organization_view
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Campaign
    template_name = 'campaigns/show.html'
    context_object_name = 'campaign'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        broker_running = is_celery_running()

        if not broker_running:
            messages.add_message(self.request, messages.ERROR, _broker_is_not_running_msg)
        c = self.object

        context['is_broker_running'] = broker_running

        context['total_notifications'] = c.notifications.count()
        context['editable'] = not is_campaign_launched(c.id)

        return context

    def get_queryset(self):
        return super(DetailView, self).get_queryset(). \
            prefetch_related('notifications__contact'). \
            annotate(
            failed=Sum(
                Case(
                    When(notifications__status=-1, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            sent=Sum(
                Case(
                    When(notifications__status=1, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            in_progress=Sum(
                Case(
                    When(notifications__status=0, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            )
        )


@organization_view
class CreateView(RequestAwareFormViewMixin, LoginRequiredMixin, generic.CreateView):
    model = Campaign
    template_name = 'campaigns/new.html'
    form_class = CampaignForm

    def get_success_url(self):
        return reverse('campaigns:show', args=[self.object.id])

    def get_form_kwargs(self):
        form_kwargs = super(CreateView, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        organization = self.request.organization
        credit = Credit.get_credit_amount(organization) if organization else 0
        if credit == 0:
            # TODO: Proposer le lien dans le flash message pour ajouter du credit ?
            messages.add_message(
                self.request, messages.WARNING,
                _("Attention ! Vous n'avez plus de crédit."))
        return form_kwargs


# TODO change notifications when campaign's contacts group is updated. Signal ?
@organization_view
class EditView(RequestAwareFormViewMixin, LoginRequiredMixin, generic.UpdateView):
    model = Campaign
    template_name = 'campaigns/edit.html'
    form_class = CampaignForm

    def get_success_url(self):
        return reverse('campaigns:show', args=[self.object.id])

    def get_form_kwargs(self):
        form_kwargs = super(EditView, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs


@login_required
def campaign_notify(request, campaign_id):
    broker_running = is_celery_running()

    if broker_running:
        notify_campaign.delay(campaign_id)

    return HttpResponseRedirect(reverse('campaigns:show', args=(campaign_id,)))


@login_required
def notify(request, campaign_id, notification_id):
    broker_running = is_celery_running()

    if broker_running:
        messages.add_message(request, messages.SUCCESS,
                             'La notification %s est en cours de traitement !' % notification_id)
        notify_task.delay(campaign_id, notification_id)
    else:
        messages.add_message(request, messages.ERROR, _broker_is_not_running_msg)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

djotali/core/views.py
# coding: utf-8
from django.core.paginator import Paginator
from django.views.generic.edit import ModelFormMixin


def paginate_in_context(request, objects, context, objects_name_in_context, per_page=10):
    page = int(request.GET.get('page', '1'))
    notifications_paginator = Paginator(objects.all(), per_page)
    notifications_page = notifications_paginator.page(page)
    context[objects_name_in_context] = context['page_obj'] = notifications_page
    context['is_paginated'] = notifications_page.has_other_pages()
    context['paginator'] = notifications_paginator


class RequestAwareFormViewMixin(ModelFormMixin):
    def get_form_kwargs(self):
        form_kwargs = super(RequestAwareFormViewMixin, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs


class ViewUtilsMixin:
    @staticmethod
    def _get_post_dict(request):
        return request.POST.dict()

djotali/dashboard/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from djotali.billing.models import Credit
from djotali.campaigns.models import Campaign, Notification
from djotali.contacts.models import Contact


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if hasattr(self.request, 'organization'):
            organization = self.request.organization
            context['total_credit'] = Credit.org_objects.get_queryset_for_organization(organization).first().credit
            context['total_contacts'] = Contact.org_objects.get_queryset_for_organization(organization).count()
            context['sent_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=1).count()
            context['failed_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=-1).count()
            context['next_campaigns'] = Campaign.get_closest_campaigns_query_set().filter(organization=organization)[:5]
        return context

djotali/templates/core/partials/_breadcrumbs.html
<div class="col-lg-8 col-sm-8 col-md-8 col-xs-12">
    <ol class="breadcrumb">
        <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
        {% if breadcrumbs %}
            {% for breadcrumb in breadcrumbs %}
                {% if breadcrumb.url %}
                    <li><a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a></li>
                {% else %}
                    <li class="active">{{ breadcrumb.title }}</li>
                {% endif %}
            {% endfor %}
        {% endif %}
    </ol>
</div>

djotali/templates/core/partials/_logout.html
<form method="post" action="{% url 'account_logout' %}">
    {% csrf_token %}
    {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <button class="form-control text-danger" type="submit"><i class="fa fa-power-off"></i>Se déconnecter</button>
</form>

djotali/templates/core/partials/flash_messages.html
{% if messages %}
    {% for message in messages %}

        {% if message.tags %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

djotali/templates/core/partials/navbar.html
{% load static %}
{% load hijack_tags %}

<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <!-- Toggle icon for mobile view -->
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse"
           data-target=".navbar-collapse"><i class="ti-menu"></i></a>
        <!-- Logo -->
        <div class="top-left-part" style="height: 100%">
            <a class="logo" href="#">
                <!-- Logo icon image, you can use font-icon also -->
                <b><img src="{% static 'plugins/images/djotali_white_transparent_48_48.png' %}" alt="home"/></b>
                <!-- Logo text image you can use text also -->
                <span class="hidden-xs"></span>
            </a>
        </div>
        <!-- /Logo -->
        <!-- Toggle icon -->
        <ul class="nav navbar-top-links navbar-left hidden-xs">
            <li>
                <a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light">
                    <i class="icon-arrow-left-circle ti-menu"></i>
                </a>
            </li>
            {% hijack_notification %}
        </ul>
        <ul class="nav navbar-top-links navbar-right pull-right">
            {% if not request|is_hijacked and request.user and request.user.is_staff %}
                <!-- .User hijack -->
                <li style="margin-top: 1em;">
                    <form method="post" onsubmit="return hijackUser(this);">
                        {% csrf_token %}
                        <input type="text" class="form-control small" id="id_hijacked_username" name="hijacked_username" required placeholder="Username to hijack">
                    </form>
                </li>
                <script>
                    function hijackUser(hijackForm) {
                        var hijackedUsername = document.getElementById('id_hijacked_username').value;
                        hijackForm.action = '/hijack/username/' + hijackedUsername + '/';
                        hijackForm.submit();
                    }
                </script>
            {% endif %}
            <!-- .Billing dropdown -->
            <li class="dropdown">
                <a aria-expanded="false" data-toggle="dropdown" class="btn dropdown-toggle waves-effect waves-light">
                    Cr&eacute;dit: {{ request.credit }}
                </a>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="{% url 'billing:index' %}">Facturation</a></li>
                </ul>
            </li>
            <!-- /.Billing dropdown -->
            <li class="dropdown">
                <a aria-expanded="false" data-toggle="dropdown" class="btn dropdown-toggle waves-effect waves-light" type="button">
                    <i class="fa fa-plus m-r-5"></i>
                    Ajouter
                </a>
                <ul role="menu" class="dropdown-menu">
                    <li><a href="{% url 'contacts:new' %}">Contact</a></li>
                    <li><a href="{% url 'contacts-groups:new' %}">Groupe de contacts</a></li>
                    <li><a href="{% url 'campaigns:new' %}">Campagne</a></li>
                </ul>
            </li>
            <!-- .user dropdown -->
            {% if request.user.is_authenticated %}
                <li class="dropdown">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
                        <span class="hide-menu">
                            <b>
                                {{ request.user.username | slice:":17" }}{% if request.user.username|length >= 17 %}... {% endif %}
                            </b>
                        </span>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated flipInY">
                        {% if profile_is_organization_admin %}
                            <li><a href="{% url 'profile:organization-users' %}"><i class="icon-people"></i> Utilisateurs</a></li>
                        {% endif %}
                        <li role="separator" class="divider"></li>
                        <li>
                            {% include 'core/partials/_logout.html' %}
                        </li>
                    </ul>
                    <!-- /.user dropdown-user -->
                </li>
            {% endif %}
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-static-side -->
</nav>

djotali/templates/core/partials/pagination.html
{% load core_extras %}
<nav aria-label="Page navigation example">
    {% with request.GET.urlencode as params %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">
                        <i class="fa fa-angle-left"></i>
                        <span class="sr-only">Précédent</span>
                    </a>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <a class="page-link">
                    Page {{ page_obj.number }} sur {{ paginator.num_pages }}
                </a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{% relative_url page_obj.next_page_number 'page' params %}">
                        <i class="fa fa-angle-right"></i>
                        <span class="sr-only">Suivant</span>
                    </a>
                </li>
            {% endif %}

        </ul>
    {% endwith %}
</nav>

djotali/templates/core/partials/sidebar.html
{% load static %}
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            {% if request.user.is_authenticated %}
                <!-- User profile-->
                <div style="background: url({% static 'plugins/images/profile-menu.png' %}) center center/cover no-repeat;">
                    <li class="user-pro">
                        <a href="#" class="waves-effect">
                        <span class="hide-menu">
                            <div><h4>{{ request.organization }}</h4></div>
                            {% if profile_is_organization_admin %}
                                <i class="fa fa-user-md"></i>
                            {% endif %}
                            {{ request.user.username | slice:":17" }}{% if request.user.username|length >= 17 %}... {% endif %}
                            <span class="fa arrow"></span>
                        </span>
                        </a>
                        <ul class="nav nav-second-level">
                            {% if profile_is_organization_admin %}
                                <li><a href="{% url 'profile:organization-users' %}"><i class="icon-people"></i> Utilisateurs</a></li>
                            {% endif %}
                            <li>
                                {% include 'core/partials/_logout.html' %}
                            </li>
                        </ul>
                    </li>
                </div>
                <!-- User profile-->

                <li>
                    <a href="{% url 'dashboard:index' %}" class="waves-effect">
                        <i data-icon="v" class="icon-screen-desktop fa-fw"></i>
                        <span class="hide-menu">
                        Dashboard
                    </span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'campaigns:index' %}" class="waves-effect">
                        <i data-icon="P" class="icon-rocket fa-fw"></i>
                        <span class="hide-menu">
                        Campagnes
                    </span>
                    </a>
                </li>

                <li>
                    <a href="#" class="waves-effect">
                        <i data-icon="P" class="icon-user fa-fw"></i>
                        <span class="hide-menu">
                        Contacts
                        <span class="fa arrow"></span>
                    </span>
                    </a>

                    <ul class="nav nav-second-level">
                        <li>
                            <a href="{% url 'contacts:index' %}">
                                Tous les contacts
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'contacts-groups:index' %}">
                                Groupes de Contacts
                            </a>
                        </li>
                        <li>
                        <a href="{% url 'contacts:import' %}">
                            Importer
                        </a>
                    </li>
                    </ul>
                </li>

                {% if request.user.is_admin %}
                    <li>
                        <a href="{% url 'admin:index' %}" class="waves-effect" target="_blank">
                            <i data-icon="P" class="icon-settings fa-fw"></i>
                            <span class="hide-menu">
                                Administration
                            </span>
                        </a>
                    </li>

                {% endif %}
            {% endif %}

        </ul>
    </div>
</div>