djotali/billing/urls.py
# coding: utf8

from django.conf.urls import url

from djotali.billing import views

app_name = 'billing'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

djotali/core/urls.py
# coding: utf8

app_name = 'core'
urlpatterns = [
    # url(r'^(?P<message_id>[0-9]+)/$', views.IndexView.as_view(), name='index')
]

djotali/profile/urls.py
# coding: utf-8
from django.conf.urls import url

from djotali.profile import views

app_name = 'profile'
urlpatterns = [
    url(r'^organization-users$', views.OrganizationUsersView.as_view(), name='organization-users'),
    url(r'^activate-users$', views.ActivateOrganizationUsersView.as_view(), name='activate-users'),
    url(r'^invite-users$', views.InviteOrganizationUserView.as_view(), name='invite-users'),
    url(r'^invitation$', views.InvitationView.as_view(), name='invitation'),
]

djotali/urls.py
# coding: utf-8
"""djotali URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from djotali.contacts.views import ContactViewSet, ContactsGroupsContactsViewSet
from djotali.profile.views import OrganizationsView

router = routers.DefaultRouter()
router.register(r'contacts', ContactViewSet)
router.register(r'contacts-groups/(?P<group_id>\d+)/contacts', ContactsGroupsContactsViewSet)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(reverse('dashboard:index'))),
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('djotali.core.urls')),
    url(r'^dashboard/', include('djotali.dashboard.urls')),
    url(r'^contacts/', include('djotali.contacts.urls')),
    url(r'^contacts-groups/', include('djotali.contacts.groups_urls')),
    url(r'^login/', TemplateView.as_view(template_name='core/login.html')),
    url(r'^campaigns/', include('djotali.campaigns.urls')),
    url(r'^billing/', include('djotali.billing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('djotali.profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/organizations/(?P<organization_name>[\S ]+)', OrganizationsView.as_view()),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token-auth/', obtain_jwt_token),
    url(r'^hijack/', include('hijack.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

djotali/billing/models.py
from uuid import uuid4

from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction
from django.db.models import F
from django_prices.models import PriceField
from prices import Price
from satchless.item import Item, ItemLine

from djotali.billing.exceptions import NotEnoughCredit
from djotali.campaigns.models import Campaign
from djotali.core.models import TrackedModel
from djotali.profile.models import AbstractOrganizationAsset


class Credit(TrackedModel, AbstractOrganizationAsset):
    credit = models.IntegerField()

    @staticmethod
    def get_credit_amount(organization):
        return Credit.objects.get(organization=organization).credit

    class Meta:
        unique_together = ('organization',)


class CampaignAllocatedCredit(TrackedModel, AbstractOrganizationAsset):
    allocated_credit = models.IntegerField()
    campaign = models.OneToOneField(Campaign, )

    @staticmethod
    def allocate(campaign, credit_to_allocate):
        organization = campaign.organization
        organization_credit = Credit.objects.get(organization=organization).credit
        if organization_credit < credit_to_allocate:
            raise NotEnoughCredit
        Credit.objects.filter(organization=organization).update(credit=organization_credit - credit_to_allocate)
        campaign_allocated_credit = CampaignAllocatedCredit.all.update_or_create(campaign=campaign, defaults={
            'allocated_credit': credit_to_allocate,
            'organization': campaign.organization,
            'is_removed': False
        })
        return campaign_allocated_credit

    @staticmethod
    def consume_one(campaign_id):
        with transaction.atomic():
            allocated_credit = CampaignAllocatedCredit.objects.get(campaign_id=campaign_id)
            allocated_credit.allocated_credit -= 1
            allocated_credit.save()
            if allocated_credit.allocated_credit < 1:
                allocated_credit.delete()
            return allocated_credit

    @staticmethod
    def deallocate_one(campaign_id):
        with transaction.atomic():
            if not CampaignAllocatedCredit.objects.filter(campaign_id=campaign_id).first():
                return
            allocated_credit = CampaignAllocatedCredit.consume_one(campaign_id)
            CampaignAllocatedCredit._add_to_credit(allocated_credit.organization, 1)

    @staticmethod
    def deallocate_and_credit(campaign_id):
        with transaction.atomic():
            allocated_credit = CampaignAllocatedCredit.objects.filter(campaign_id=campaign_id).first()
            if not allocated_credit:
                # In this case it has probably been de-allocated by consume_one if no allocated credit was left
                return
            CampaignAllocatedCredit._add_to_credit(allocated_credit.organization, allocated_credit.allocated_credit)
            allocated_credit.delete()

    @staticmethod
    def _add_to_credit(organization, amount):
        Credit.objects.filter(organization=organization).update(credit=F('credit') + amount)


class ProductManager(models.Manager):
    def get_published_products(self):
        return self.get_queryset().filter(is_published=True)


class Product(TrackedModel, Item):
    name = models.CharField(max_length=100, blank=True, unique=True)
    description = models.TextField()
    price = PriceField(currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2)
    is_published = models.BooleanField(default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    def get_price_per_item(self, **kwargs):
        return self.price

    def description_lines(self):
        return self.description.split('\n')

    def formatted_net_price(self):
        # TODO change when there will be i18n
        return '{:,}'.format(self.price.net).rstrip('0').rstrip('.').replace(',', '.')


class Cart(TrackedModel, AbstractOrganizationAsset):
    """A shopping cart."""
    token = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    total = PriceField(currency=settings.DEFAULT_CURRENCY, max_digits=12, decimal_places=2, default=0)

    # pylint: disable=R0201
    def get_subtotal(self, item, **kwargs):
        """Return the cost of a cart line."""
        return item.get_total(**kwargs)

    def get_total(self, **kwargs):
        """Return the total cost of the cart prior to shipping."""
        subtotals = [
            self.get_subtotal(item, **kwargs) for item in self.lines.all()]
        if not subtotals:
            raise AttributeError('Calling get_total() on an empty item set')
        zero = Price(0, currency=settings.DEFAULT_CURRENCY)
        return sum(subtotals, zero)

    def count(self):
        """Return the total quantity in cart."""
        lines = self.lines.all()
        return lines.aggregate(total_quantity=models.Sum('quantity'))

    def clear(self):
        """Remove the cart."""
        self.delete()

    def create_line(self, product, quantity):
        """Create a cart line for given variant, quantity and optional data.
        The `data` parameter may be used to differentiate between items with
        different customization options.
        """
        return self.lines.create(product=product, quantity=quantity)

    def get_line(self, product):
        """Return a line matching the given variant and data if any."""
        all_lines = self.lines.all()
        line = [line for line in all_lines if line.variant_id == product.id]
        if line:
            return line[0]

    def add(self, variant, quantity=1, replace=False):
        """Add a product to cart.
        The `data` parameter may be used to differentiate between items with
        different customization options.
        If `replace` is truthy then any previous quantity is discarded instead
        of added to.
        """
        cart_line, dummy_created = self.lines.get_or_create(variant=variant, defaults={'quantity': 0})

        if replace:
            new_quantity = quantity
        else:
            new_quantity = cart_line.quantity + quantity

        if new_quantity < 0:
            raise ValueError('%r is not a valid quantity (results in %r)' % (quantity, new_quantity))

        cart_line.quantity = new_quantity

        if not cart_line.quantity:
            cart_line.delete()
        else:
            cart_line.save(update_fields=['quantity'])


class CartLine(TrackedModel, ItemLine):
    """A single cart line.
    Multiple lines in the same cart can refer to the same product variant if
    their `data` field is different.
    """

    cart = models.ForeignKey(Cart, related_name='lines', on_delete=models.CASCADE)
    product = models.ForeignKey('billing.Product', related_name='+', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(999)])

    class Meta:
        unique_together = ('cart', 'product',)

    def __eq__(self, other):
        if not isinstance(other, CartLine):
            return NotImplemented

        return self.product == other.product and self.quantity == other.quantity

    def __ne__(self, other):
        return not self == other  # pragma: no cover

    def __repr__(self):
        return 'CartLine(product=%r, quantity=%r)' % (self.product, self.quantity)

    def __getstate__(self):
        return self.product, self.quantity

    def __setstate__(self, data):
        self.product, self.quantity = data

    def get_quantity(self, **kwargs):
        """Return the line's quantity."""
        return self.quantity

    # pylint: disable=W0221
    def get_price_per_item(self, discounts=None, **kwargs):
        """Return the unit price of the line."""
        return self.product.get_price_per_item(discounts=discounts, **kwargs)

djotali/dashboard/models.py
# coding: utf-8

djotali/profile/models.py
# Create your models here.
from django.db import models
from model_utils.managers import SoftDeletableManager
from organizations.models import Organization
from rest_framework import serializers

from djotali.core.models import TrackedModel


class OrganizationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Organization
        fields = ('name',)


class OrganizationAssetManager(SoftDeletableManager):
    def get_queryset_for_organization(self, organization):
        return super(OrganizationAssetManager, self).get_queryset().filter(organization__id=organization.id)


class AbstractOrganizationAsset(models.Model):
    organization = models.ForeignKey(Organization)

    org_objects = OrganizationAssetManager()

    class Meta:
        abstract = True


class Sender(TrackedModel, AbstractOrganizationAsset):
    sender_id = models.CharField(max_length=11, blank=False, null=False)

djotali/campaigns/forms.py
# coding: utf-8

from django import forms

from djotali.campaigns.models import Campaign
from djotali.campaigns.widgets import CampaignContactsGroupBoundModelsSelectWidget, SmsWidget
from djotali.contacts.models import ContactsGroup
from djotali.core.forms import BaseForm
from djotali.core.widgets import DateTimeFieldWidget
from djotali.profile.models import Sender


class CampaignForm(BaseForm):
    class Meta:
        model = Campaign
        fields = ['name', 'start_date', 'message', 'contacts_group']

    name = forms.CharField(label='Nom')
    start_date = forms.DateTimeField(label='Lancement', widget=DateTimeFieldWidget)
    message = forms.Field(label='Message', widget=SmsWidget)
    contacts_group = forms.ModelChoiceField(label='Groupe de contacts', queryset=ContactsGroup.objects,
                                            widget=CampaignContactsGroupBoundModelsSelectWidget,
                                            empty_label='Tous les contacts', required=False)

    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.fields['contacts_group'].queryset = ContactsGroup.org_objects.get_queryset_for_organization(self.request.organization)
        self.fields['message'].widget.attrs['sender'] = Sender.org_objects.get_queryset_for_organization(self.request.organization).first().sender_id

djotali/core/forms.py
# coding: utf-8
from django.forms import ModelForm


class BaseForm(ModelForm):
    required_css_class = 'form-group'

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            setattr(self, 'request', kwargs.pop('request'))
        super(BaseForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        if hasattr(self, 'request'):
            self.instance.organization = self.request.organization
        return super().save(commit)

djotali/billing/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.views import generic

from djotali.billing.models import Credit, CampaignAllocatedCredit, Product


# TODO becomes a generic.ListView when we will introduce transactions
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'billing/show.html'
    queryset = Product.objects.get_published_products
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['credit'] = Credit.objects.get(organization=self.request.organization)
        allocated_credit = \
            CampaignAllocatedCredit.objects.filter(organization=self.request.organization).aggregate(Sum('allocated_credit'))['allocated_credit__sum']
        data['allocated_credit'] = allocated_credit if allocated_credit else 0
        return data

djotali/core/views.py
# coding: utf-8
from django.core.paginator import Paginator
from django.views.generic.edit import ModelFormMixin


def paginate_in_context(request, objects, context, objects_name_in_context, per_page=10):
    page = int(request.GET.get('page', '1'))
    notifications_paginator = Paginator(objects.all(), per_page)
    notifications_page = notifications_paginator.page(page)
    context[objects_name_in_context] = context['page_obj'] = notifications_page
    context['is_paginated'] = notifications_page.has_other_pages()
    context['paginator'] = notifications_paginator


class RequestAwareFormViewMixin(ModelFormMixin):
    def get_form_kwargs(self):
        form_kwargs = super(RequestAwareFormViewMixin, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs


class ViewUtilsMixin:
    @staticmethod
    def _get_post_dict(request):
        return request.POST.dict()

djotali/dashboard/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from djotali.billing.models import Credit
from djotali.campaigns.models import Campaign, Notification
from djotali.contacts.models import Contact


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if hasattr(self.request, 'organization'):
            organization = self.request.organization
            context['total_credit'] = Credit.org_objects.get_queryset_for_organization(organization).first().credit
            context['total_contacts'] = Contact.org_objects.get_queryset_for_organization(organization).count()
            context['sent_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=1).count()
            context['failed_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=-1).count()
            context['next_campaigns'] = Campaign.get_closest_campaigns_query_set().filter(organization=organization)[:5]
        return context

djotali/templates/profile/invitation.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Invitation à créer un compte{% endblock %}
{% block body %}
    <section id="wrapper" class="login-register">
        <div class="login-box">
            <div class="white-box">
                <form class="form-horizontal form-material" id="signupform" method="POST" action="{% url 'profile:invitation' %}">
                    <h3 class="box-title m-b-20">Invitation à créer un compte</h3>
                    {% csrf_token %}
                    {% include "account/snippets/errors.html" %}
                    <input type="hidden" id="id_token" name="token" value="{{ token }}"/>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input type="hidden" name="email" id="id_email" value="{{ email }}">
                            <input type="hidden" name="username" id="id_username" value="{{ email }}">
                            Email : {{ email }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input id="id_organization" name="organization" type="hidden" value="{{ organization }}">
                            Entreprise : {{ organization }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input id="id_password1" name="password1" type="password" class="form-control"
                                   required placeholder="Mot de passe">
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">
                                Créer le compte
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}
{% block scripts %}
    {{ block.super }}
{% endblock %}

djotali/templates/profile/invitation_email_body.html
{% load static core_extras %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Invitation - Djotali</title>
</head>
<body style="margin:0px; background: #f8f8f8; ">
<div width="100%"
     style="background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;">
    <div style="max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px">
        <table border="0" cellpadding="0" cellspacing="0" style="width: 100%; margin-bottom: 20px">
            <tbody>
            <tr>
                <td style="vertical-align: top; padding-bottom:30px;" align="center">
                    <a href="{% abs_url '/' %}" target="_blank">
                        <img src="{% static_abs_url 'plugins/images/djotali_black_transparent_48_48.png' %}"
                             alt="Djotali" style="border:none"><br/>
                    </a>
                </td>
            </tr>
            </tbody>
        </table>
        <div style="padding: 40px; background: #fff;">
            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                <tbody>
                <tr>
                    <td>

                        <b>Bonjour,</b>
                        <p>L'administrateur du compte "{{ organization }}" vous invite &agrave; cr&eacute;er un compte
                            sur l'application Djotali.</p>
                        <p>Cliquer sur le lien ci-dessous pour créer votre compte.</p>
                        <a href="{{ invitation_url|safe }}"
                           style="display: inline-block; padding: 11px 30px; margin: 20px 0px 30px; font-size: 15px; color: #fff; background: #00c0c8; border-radius: 60px; text-decoration:none;">
                            Accepter l&rsquo;invitation</a>
                        <p>Djotali vous rapproche de vos clients en facilitant le lancement de campagnes par SMS.</p>
                        <b>- A bientôt</b>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div style="text-align: center; font-size: 12px; color: #b2b2b5; margin-top: 20px">
            <p>Powered by Djotali</p>
        </div>
    </div>
</div>
</body>
</html>

djotali/templates/profile/new_signup_email_body.html
{% load static core_extras %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>Nouvelle connexion - Djotali</title>
</head>
<body style="margin:0px; background: #f8f8f8; ">
<div width="100%" style="background: #f8f8f8; padding: 0px 0px; font-family:arial; line-height:28px; height:100%;  width: 100%; color: #514d6a;">
    <div style="max-width: 700px; padding:50px 0;  margin: 0px auto; font-size: 14px">
        <table border="0" cellpadding="0" cellspacing="0" style="width: 100%; margin-bottom: 20px">
            <tbody>
            <tr>
                <td style="vertical-align: top; padding-bottom:30px;" align="center">
                    <a href="{% abs_url '/' %}" target="_blank">
                        <img src="{% static_abs_url 'plugins/images/djotali_black_transparent_48_48.png' %}"
                             alt="Djotali" style="border:none"><br/>
                    </a>
                </td>
            </tr>
            </tbody>
        </table>
        <div style="padding: 40px; background: #fff;">
            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                <tbody>
                <tr>
                    <td>

                        <b>Bonjour,</b>
                        <p>L'utilisateur ayant pour email {{ signup_email }} vient de s'enregistrer sur votre compte {{ organization }}.</p>
                        <p>Merci d'ignorer ce mail si vous avez invité cet utilisateur.</p>
                        <p>Cliquer sur le lien ci-dessous pour créer votre compte.</p>
                        <a href="{{ activate_url|safe }}" style="display: inline-block; padding: 11px 30px; margin: 20px 0px 30px; font-size: 15px; color: #fff; background: #00c0c8; border-radius: 60px; text-decoration:none;">
                            Sinon cliquez pour désactiver le compte
                        </a>
                        <p>Djotali vous rapproche de vos clients en facilitant le lancement de campagnes par SMS.</p>
                        <b>- A bientôt</b>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div style="text-align: center; font-size: 12px; color: #b2b2b5; margin-top: 20px">
            <p>Powered by Djotali</p>
        </div>
    </div>
</div>
</body>
</html>

djotali/templates/profile/organization_users.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}Utilisateurs{% endblock %}

{% block content %}
    <div class="row bg-title">
        <!-- .page title -->
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Utilisateurs</h4>
        </div>
        <!-- /.page title -->
        <!-- .breadcrumb -->
        <div class="col-lg-8 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a>Profil</a></li>
                <li class="active">
                    Utilisateurs
                </li>
            </ol>
        </div>
        <!-- /.breadcrumb -->
    </div>
    <!-- .row -->
    <div class="row">
        <div class="col-md-12">
            {% include 'core/partials/flash_messages.html' %}
            <div class="white-box">
                <form action="{% url 'profile:invite-users' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="offset-1 col-lg-9">
                            <div class="form-group ">
                                <input id="id_email" name="email" type="email" class="form-control" placeholder="Saisir l'email de l'utilisateur que vous voulez inviter">
                            </div>
                        </div>
                        <div class="col-lg-2 form-group">
                            <input type="submit" class="btn btn-success" value="Inviter"/>
                        </div>
                    </div>
                </form>
            </div>
            {% if users %}
                <div class="white-box">
                    <h3 class="box-title m-b-0">Activer ou désactiver vos utilisateurs</h3>
                    <form action="{% url 'profile:activate-users' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="offset-1 col-lg-9 bt-switch">
                                {% for user in users %}
                                    <div class="row m-t-20">
                                        <div class="col-lg-12 form-group">
                                            <input name="activate_{{ user.id }}" id="id_activate_{{ user.id }}"
                                                    {% if user.is_active %} checked {% endif %}
                                                   type="checkbox" data-on-color="success" data-off-color="danger" data-size="normal">
                                            <label for="id_activate_{{ user.id }}" style="margin-left: 5em">{{ user }}</label>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <div class="col-lg-2 form-group">
                                <input type="submit" class="btn btn-sticky btn-success" value="Valider"/>
                            </div>
                        </div>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-switch/bootstrap-switch.min.css' %}">
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'plugins/bootstrap-switch/bootstrap-switch.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            // Activate button switches
            $(".bt-switch input[type='checkbox'], .bt-switch input[type='radio']").bootstrapSwitch();
        });
    </script>
{% endblock %}