djotali/billing/urls.py
# coding: utf8

from django.conf.urls import url

from djotali.billing import views

app_name = 'billing'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

djotali/campaigns/urls.py
# coding: utf8

from django.conf.urls import url, include

from djotali.campaigns import views
from djotali.campaigns.api import router

app_name = 'campaigns'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^new$', views.CreateView.as_view(), name='new'),
    url(r'^(?P<campaign_id>\d+)/notify$', views.campaign_notify, name='notify_campaign'),
    url(r'^(?P<pk>\d+)/notifications$', views.NotificationsView.as_view(), name='notifications'),
    url(r'^(?P<pk>\d+)$', views.DetailView.as_view(), name='show'),
    url(r'^(?P<pk>\d+)/edit$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<campaign_id>\d+)/notifications/(?P<notification_id>\d+)/notify$', views.notify, name='core_notify'),
    # url(r'^(?P<message_id>[0-9]+)/$', views.IndexView.as_view(), name='index')
    url(r'^api/', include(router.urls, namespace='api_campaign'))
]

djotali/core/urls.py
# coding: utf8

app_name = 'core'
urlpatterns = [
    # url(r'^(?P<message_id>[0-9]+)/$', views.IndexView.as_view(), name='index')
]

djotali/profile/urls.py
# coding: utf-8
from django.conf.urls import url

from djotali.profile import views

app_name = 'profile'
urlpatterns = [
    url(r'^organization-users$', views.OrganizationUsersView.as_view(), name='organization-users'),
    url(r'^activate-users$', views.ActivateOrganizationUsersView.as_view(), name='activate-users'),
    url(r'^invite-users$', views.InviteOrganizationUserView.as_view(), name='invite-users'),
    url(r'^invitation$', views.InvitationView.as_view(), name='invitation'),
]

djotali/urls.py
# coding: utf-8
"""djotali URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token

from djotali.contacts.views import ContactViewSet, ContactsGroupsContactsViewSet
from djotali.profile.views import OrganizationsView

router = routers.DefaultRouter()
router.register(r'contacts', ContactViewSet)
router.register(r'contacts-groups/(?P<group_id>\d+)/contacts', ContactsGroupsContactsViewSet)

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(reverse('dashboard:index'))),
    url(r'^admin/', admin.site.urls),
    url(r'^core/', include('djotali.core.urls')),
    url(r'^dashboard/', include('djotali.dashboard.urls')),
    url(r'^contacts/', include('djotali.contacts.urls')),
    url(r'^contacts-groups/', include('djotali.contacts.groups_urls')),
    url(r'^login/', TemplateView.as_view(template_name='core/login.html')),
    url(r'^campaigns/', include('djotali.campaigns.urls')),
    url(r'^billing/', include('djotali.billing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile/', include('djotali.profile.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^api/organizations/(?P<organization_name>[\S ]+)', OrganizationsView.as_view()),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token-auth/', obtain_jwt_token),
    url(r'^hijack/', include('hijack.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [url(r'^__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

djotali/core/models.py
# coding: utf-8
from django.db.backends.oracle.functions import IntervalToSeconds
from django.db.models import Manager
from model_utils.models import SoftDeletableModel, TimeStampedModel


class IntervalToSecondsNoSqlite(IntervalToSeconds):
    def __init__(self, expression, **extra):
        super(IntervalToSecondsNoSqlite, self).__init__(expression, **extra)

    def as_sql(self, compiler, connection, function=None, template=None, arg_joiner=None, **extra_context):
        if connection.vendor == 'sqlite':
            template = '%(expressions)s'
        return super().as_sql(compiler, connection, function, template, arg_joiner, **extra_context)


class TrackedModel(TimeStampedModel, SoftDeletableModel):
    all = Manager()

    class Meta:
        abstract = True

djotali/dashboard/models.py
# coding: utf-8

djotali/campaigns/forms.py
# coding: utf-8

from django import forms

from djotali.campaigns.models import Campaign
from djotali.campaigns.widgets import CampaignContactsGroupBoundModelsSelectWidget, SmsWidget
from djotali.contacts.models import ContactsGroup
from djotali.core.forms import BaseForm
from djotali.core.widgets import DateTimeFieldWidget
from djotali.profile.models import Sender


class CampaignForm(BaseForm):
    class Meta:
        model = Campaign
        fields = ['name', 'start_date', 'message', 'contacts_group']

    name = forms.CharField(label='Nom')
    start_date = forms.DateTimeField(label='Lancement', widget=DateTimeFieldWidget)
    message = forms.Field(label='Message', widget=SmsWidget)
    contacts_group = forms.ModelChoiceField(label='Groupe de contacts', queryset=ContactsGroup.objects,
                                            widget=CampaignContactsGroupBoundModelsSelectWidget,
                                            empty_label='Tous les contacts', required=False)

    def __init__(self, *args, **kwargs):
        super(CampaignForm, self).__init__(*args, **kwargs)
        self.fields['contacts_group'].queryset = ContactsGroup.org_objects.get_queryset_for_organization(self.request.organization)
        self.fields['message'].widget.attrs['sender'] = Sender.org_objects.get_queryset_for_organization(self.request.organization).first().sender_id

djotali/contacts/forms.py
# coding: utf-8
import phonenumbers
from django.core.exceptions import ValidationError
from django.forms import CharField, Field, FileField
from django.forms.forms import Form
from django.forms.widgets import FileInput
from django.utils.translation import ugettext_lazy as _
from phonenumbers.phonenumberutil import NumberParseException

from djotali.contacts.models import Contact, ContactsGroup
from djotali.contacts.widgets import ContactsWidget
from djotali.core.forms import BaseForm


class ContactForm(BaseForm):
    # Max number of characters of a senegalese telephone number including whitespaces
    phone_number = CharField(initial='+221 ', label='Téléphone', max_length=17)
    first_name = CharField(label='Prénom')
    last_name = CharField(label='Nom')

    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'phone_number']

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        error_message = 'Le numéro de téléphone entré est erroné'
        try:
            if not phonenumbers.is_valid_number(phonenumbers.parse(phone_number, 'SN')):
                raise ValidationError(_(error_message), code='invalid')
        except NumberParseException:
            raise ValidationError(_(error_message), code='invalid')

        return phone_number


class ContactsGroupForm(BaseForm):
    name = CharField(label='Nom')
    contacts = Field(label='Contacts', widget=ContactsWidget)

    class Meta:
        model = ContactsGroup
        fields = ['name', 'contacts']


class ImportContactsForm(Form):
    file = FileField(widget=FileInput(attrs={'class': 'dropify'}))

djotali/core/forms.py
# coding: utf-8
from django.forms import ModelForm


class BaseForm(ModelForm):
    required_css_class = 'form-group'

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            setattr(self, 'request', kwargs.pop('request'))
        super(BaseForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        if hasattr(self, 'request'):
            self.instance.organization = self.request.organization
        return super().save(commit)

djotali/billing/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.views import generic

from djotali.billing.models import Credit, CampaignAllocatedCredit, Product


# TODO becomes a generic.ListView when we will introduce transactions
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'billing/show.html'
    queryset = Product.objects.get_published_products
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['credit'] = Credit.objects.get(organization=self.request.organization)
        allocated_credit = \
            CampaignAllocatedCredit.objects.filter(organization=self.request.organization).aggregate(Sum('allocated_credit'))['allocated_credit__sum']
        data['allocated_credit'] = allocated_credit if allocated_credit else 0
        return data

djotali/campaigns/views.py
# coding: utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.aggregates import Sum
from django.db.models.expressions import Case, When
from django.db.models.fields import IntegerField
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import generic
from django.utils.translation import gettext as _

from djotali.billing.models import Credit
from djotali.campaigns.forms import CampaignForm
from djotali.campaigns.models import Campaign, Notification
from djotali.campaigns.tasks import notify_campaign, notify_task, is_campaign_launched
from djotali.core.utils import is_celery_running
from djotali.core.views import paginate_in_context, RequestAwareFormViewMixin
from djotali.profile.decorators import organization_view

_broker_is_not_running_msg = 'Le broker est arrêté. Le lancement des campagnes est suspendu.'


@organization_view
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'campaigns/index.html'
    context_object_name = 'list_objects'
    paginate_by = 5
    queryset = Campaign.get_closest_campaigns_query_set()


@organization_view
class NotificationsView(LoginRequiredMixin, generic.DetailView):
    model = Campaign
    template_name = 'campaigns/notifications.html'
    context_object_name = 'campaign'

    def get_context_data(self, **kwargs):
        context = super(NotificationsView, self).get_context_data(**kwargs)
        campaign = self.object

        status = self.request.GET.get('status')
        context['status'] = status

        notifications = campaign.notifications
        if status is not None:
            notifications = notifications.filter(status=Notification.get_status_value(status))
        paginate_in_context(self.request, notifications, context, 'notifications')

        context['editable'] = not is_campaign_launched(campaign.id)

        return context


@organization_view
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Campaign
    template_name = 'campaigns/show.html'
    context_object_name = 'campaign'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        broker_running = is_celery_running()

        if not broker_running:
            messages.add_message(self.request, messages.ERROR, _broker_is_not_running_msg)
        c = self.object

        context['is_broker_running'] = broker_running

        context['total_notifications'] = c.notifications.count()
        context['editable'] = not is_campaign_launched(c.id)

        return context

    def get_queryset(self):
        return super(DetailView, self).get_queryset(). \
            prefetch_related('notifications__contact'). \
            annotate(
            failed=Sum(
                Case(
                    When(notifications__status=-1, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            sent=Sum(
                Case(
                    When(notifications__status=1, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            ),
            in_progress=Sum(
                Case(
                    When(notifications__status=0, then=1),
                    default=0,
                    output_field=IntegerField()
                )
            )
        )


@organization_view
class CreateView(RequestAwareFormViewMixin, LoginRequiredMixin, generic.CreateView):
    model = Campaign
    template_name = 'campaigns/new.html'
    form_class = CampaignForm

    def get_success_url(self):
        return reverse('campaigns:show', args=[self.object.id])

    def get_form_kwargs(self):
        form_kwargs = super(CreateView, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        organization = self.request.organization
        credit = Credit.get_credit_amount(organization) if organization else 0
        if credit == 0:
            # TODO: Proposer le lien dans le flash message pour ajouter du credit ?
            messages.add_message(
                self.request, messages.WARNING,
                _("Attention ! Vous n'avez plus de crédit."))
        return form_kwargs


# TODO change notifications when campaign's contacts group is updated. Signal ?
@organization_view
class EditView(RequestAwareFormViewMixin, LoginRequiredMixin, generic.UpdateView):
    model = Campaign
    template_name = 'campaigns/edit.html'
    form_class = CampaignForm

    def get_success_url(self):
        return reverse('campaigns:show', args=[self.object.id])

    def get_form_kwargs(self):
        form_kwargs = super(EditView, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs


@login_required
def campaign_notify(request, campaign_id):
    broker_running = is_celery_running()

    if broker_running:
        notify_campaign.delay(campaign_id)

    return HttpResponseRedirect(reverse('campaigns:show', args=(campaign_id,)))


@login_required
def notify(request, campaign_id, notification_id):
    broker_running = is_celery_running()

    if broker_running:
        messages.add_message(request, messages.SUCCESS,
                             'La notification %s est en cours de traitement !' % notification_id)
        notify_task.delay(campaign_id, notification_id)
    else:
        messages.add_message(request, messages.ERROR, _broker_is_not_running_msg)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

djotali/core/views.py
# coding: utf-8
from django.core.paginator import Paginator
from django.views.generic.edit import ModelFormMixin


def paginate_in_context(request, objects, context, objects_name_in_context, per_page=10):
    page = int(request.GET.get('page', '1'))
    notifications_paginator = Paginator(objects.all(), per_page)
    notifications_page = notifications_paginator.page(page)
    context[objects_name_in_context] = context['page_obj'] = notifications_page
    context['is_paginated'] = notifications_page.has_other_pages()
    context['paginator'] = notifications_paginator


class RequestAwareFormViewMixin(ModelFormMixin):
    def get_form_kwargs(self):
        form_kwargs = super(RequestAwareFormViewMixin, self).get_form_kwargs()
        form_kwargs.update({
            'request': self.request
        })
        return form_kwargs


class ViewUtilsMixin:
    @staticmethod
    def _get_post_dict(request):
        return request.POST.dict()

djotali/dashboard/views.py
# coding: utf-8
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from djotali.billing.models import Credit
from djotali.campaigns.models import Campaign, Notification
from djotali.contacts.models import Contact


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if hasattr(self.request, 'organization'):
            organization = self.request.organization
            context['total_credit'] = Credit.org_objects.get_queryset_for_organization(organization).first().credit
            context['total_contacts'] = Contact.org_objects.get_queryset_for_organization(organization).count()
            context['sent_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=1).count()
            context['failed_messages'] = Notification.org_objects.get_queryset_for_organization(organization).filter(status=-1).count()
            context['next_campaigns'] = Campaign.get_closest_campaigns_query_set().filter(organization=organization)[:5]
        return context

djotali/templates/campaigns/edit.html
{% extends 'core/form.html' %}
{% load static %}

{% block page-title %}&Eacute;diter la campagne{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
    <li><a href="{% url 'campaigns:index' %}">Campagnes</a></li>
    <li>
        <a href="{% url 'campaigns:show' campaign.id %}">
            {{ campaign.name | slice:":25" }}{% if campaign.name|length >= 25 %}... {% endif %}
        </a>
    </li>
    <li class="active">
        &Eacute;diter
    </li>
{% endblock %}

djotali/templates/campaigns/new.html
{% extends 'core/form.html' %}
{% load static %}

{% block page-title %}Cr&eacute;er la campagne{% endblock %}
{% block breadcrumbs %}
    <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
    <li><a href="{% url 'campaigns:index' %}">Campagnes</a></li>
    <li class="active">
        Cr&eacute;er
    </li>
{% endblock %}

djotali/templates/campaigns/notifications.html
{% extends 'core/base.html' %}
{% load contacts_extras campaigns_extras %}

{% block title %}
    Notifications - Campagne - {{ campaign.name }}
{% endblock %}

{% block content %}
    {% with campaign|can_launch_campaign as launchable %}
        <div class="row bg-title">
            <!-- .page title -->
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <h4 class="page-title">
                    {{ campaign.name }} - Notifications
                </h4>
            </div>
            <!-- /.page title -->
            <!-- .breadcrumb -->
            <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
                    <li><a href="{% url 'campaigns:index' %}">Campagnes</a></li>
                    <li>
                        <a href="{% url 'campaigns:show' campaign.id %}">
                            {{ campaign.name | slice:":25" }}{% if campaign.name|length >= 25 %}... {% endif %}
                        </a>
                    </li>
                    <li class="active">
                        Notifications
                    </li>
                </ol>
            </div>
            <!-- /.breadcrumb -->
        </div>
        <!-- .row -->

        {% if launchable %}
            <div class="row">
                <div class="offset-8 col-lg-4" style="margin-bottom: 2em">
                    <a href="{% url 'campaigns:notify_campaign' campaign.id %}" class="btn btn-success pull-right">
                        <span class="btn-label">
                            <i class="icon-paper-plane"></i>
                        </span>
                        Notifier les contacts
                    </a>
                </div>
            </div>
        {% endif %}

        <div class="row">
            <div class="col-lg-12">
                <div class="sttabs tabs-style-iconbox">
                    <nav>
                        <div class="sttabs tabs-style-iconbox">
                            <nav>
                                <ul>
                                    <li {% if not status %}class="tab-current"{% endif %}>
                                        {% if not status %}
                                            <a class="sticon icon-rocket text-white" data-icon="E">
                                                <span>Toutes</span>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'campaigns:notifications' campaign.id %}"
                                               class="sticon icon-rocket text-inversed" data-icon="E">
                                                <span>Toutes</span>
                                            </a>
                                        {% endif %}
                                    </li>
                                    <li {% if status == "SENT" %}class="tab-current"{% endif %}>
                                        {% if status == "SENT" %}
                                            <a class="sticon icon-paper-plane text-white" data-icon="&#xe016;">
                                                <span>Envoyé(s)</span>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'campaigns:notifications' campaign.id %}?status=SENT"
                                               class="sticon icon-paper-plane text-success" data-icon="&#xe01b;">
                                                <span>Envoyé(s)</span>
                                            </a>
                                        {% endif %}
                                    </li>
                                    <li {% if status == "FAILED" %}class="tab-current"{% endif %}>
                                        {% if status == "FAILED" %}
                                            <a class="sticon icon-close text-white" data-icon="&#xe016;">
                                                <span>&Eacute;choué(s)</span>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'campaigns:notifications' campaign.id %}?status=FAILED"
                                               class="sticon icon-close text-danger" data-icon="&#xe016;">
                                                <span>&Eacute;choué(s)</span>
                                            </a>
                                        {% endif %}
                                    </li>
                                    <li {% if status == "PROGRESS" %}class="tab-current"{% endif %}>
                                        {% if status == "PROGRESS" %}
                                            <a class="sticon fa ion-load-c text-white"
                                               data-icon="&#xe00b;">
                                                <span>En cours</span>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'campaigns:notifications' campaign.id %}?status=PROGRESS"
                                               class="sticon fa ion-load-c text-info" data-icon="&#xe00b;">
                                                <span>En cours</span>
                                            </a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="white-box">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead class="thead-default">
                            <tr>
                                <th>Nom</th>
                                <th>Numéro</th>
                                <th>Statut</th>
                                <th>Date d'envoi</th>
                                <th>Actions</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for n in notifications %}
                                <tr>
                                    <td>{{ n.contact }}</td>
                                    <td>
                                        <span class="label label-success label-rounded">{{ n.contact.phone_number | format_number }}</span>
                                    </td>
                                    <td>

                                        {% if n.status == -1 %}
                                            <i title="Failed"
                                               class="sent__status text-danger icon-close fa-lg help force-text-left"></i>
                                        {% elif n.status == 1 %}
                                            <i title="Sent"
                                               class="sent__status text-success force-text-left is-success fa icon-check fa-lg"></i>
                                        {% else %}
                                            <i title="Processing..."
                                               class=" text-info sent__status fa ion-load-c fa-spin help force-text-left"></i>
                                        {% endif %}
                                    </td>

                                    <td>
                                        {% if n.status == 1 %}
                                            {{ n.send_date | date:'d-m-Y h:i:s' }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if launchable %}
                                            {% if n.sendable or not n.is_sent %}
                                                <a href="{% url 'campaigns:core_notify' campaign.id n.id %}">
                                                    <i class="icon-paper-plane fa-lg"></i>
                                                </a>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% if is_paginated %}
                        <div class="d-flex flex-md-row justify-content-end bd-highlight mb-3">
                            <div class="p-2">
                                {% include 'core/partials/pagination.html' %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endwith %}

{% endblock %}